// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzJ-pygAlhtMDmtpIQnCPY1PhXjC0XhY',
    appId: '1:50821435396:web:cf7f1da384ea3a0e402551',
    messagingSenderId: '50821435396',
    projectId: 'facebook-5209b',
    authDomain: 'facebook-5209b.firebaseapp.com',
    storageBucket: 'facebook-5209b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHR0jFrbMhtjhyUCd0Frz_jft0-lZIZU',
    appId: '1:50821435396:android:809efbad61f3acef402551',
    messagingSenderId: '50821435396',
    projectId: 'facebook-5209b',
    storageBucket: 'facebook-5209b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4DlW3dSWWkaoJdDedLQY2UkfLs3DfYA',
    appId: '1:50821435396:ios:d01c84d448ce4841402551',
    messagingSenderId: '50821435396',
    projectId: 'facebook-5209b',
    storageBucket: 'facebook-5209b.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );
}
